parameters:
  ped_api_error.discrimination_strategy.base.api_base_path: /api

services:
  _defaults:
    autowire: true

  ped_api_error.api_exception_listener:
    class: PED\ApiErrorBundle\EventListener\ApiExceptionListener
    arguments: ['@ped_api_error.discrimination_strategy.base', '@ped_api_error.response_builder.base']
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  ped_api_error.discrimination_strategy.base:
    class: PED\ApiErrorBundle\Discrimination\BaseDiscriminationStrategy
    arguments: ['%ped_api_error.discrimination_strategy.base.api_base_path%']

  ped_api_error.response_builder.base:
    class: PED\ApiErrorBundle\ResponseBuilder\BaseResponseBuilder
    arguments:
      - '%kernel.debug%'
      - '@ped_api_error.exception_mapper.mapping_strategy'
      - '@ped_api_error.exception_mapper.parameters_extractor'
      - '@ped_api_error.exception_mapper.error_details_mapper'

  ped_api_error.exception_mapper.mapping_strategy:
    class: PED\ApiErrorBundle\ExceptionMapper\FqcnMappingStrategy

  ped_api_error.exception_mapper.parameters_extractor:
    class: PED\ApiErrorBundle\ExceptionMapper\ParametricExceptionExtractor

  ped_api_error.exception_mapper.error_details_mapper:
    class: PED\ApiErrorBundle\ExceptionMapper\BaseErrorDetailsMapper